### ISSUE TITLE
Files that only differ in stripped special characters collide

### ISSUE THREAD

**Issue by Sellyme** [AndrewMD888/File-Renamer#1]
**Example**: files `Dave'sFile.txt` and `DavesFile.txt` will both get converted to `DavesFile.txt` and collide. Further behaviour is undefined and likely results in an exception and script termination.

This issue can also occur if files in the directory are modified or added during the renaming process, or if the renamer is run on directories that have already been partially renamed.

**Proposed Solution**: pseudocode:

```
function check_name(new_file):
    for all files in directory:
        if file.name matches new_file.name:
            if file.content matches new_file.content:
                delete new_file
                return
            else:
                new_file.name = new_file.name + ' Copy'
                check_name(new_file) //recursively check that the new name isn't ALSO a collision
```

**Comment by AndrewMD888** [comment]
Thank you for the issue, Sellyme. I fixed this issue's core problem, which was the filename collision. Take a look at the source code now and let me know if anything you addressed above is still unaddressed, or if I missed something.

**Comment by AndrewMD888** [comment]
Closing this issue as the main problem with filename collision has been fixed. I will make a decision later on how I will handle renaming or deleting files with the same name that have the exact same content. Addressing that will come in a future update.
